services:
  syncserver:
    build: .
    container_name: syncserver
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Chita
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend

  migrate:
    build: .
    profiles:
      - tools
    env_file:
      - .env
    environment:
      - TZ=Asia/Chita
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: ["python", "-m", "alembic", "upgrade", "head"]
    networks:
      - backend

networks:
  backend:
    external: true