CREATE TABLE IF NOT EXISTS sites (
    id UUID PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sites_code ON sites(code);



CREATE TABLE IF NOT EXISTS devices (
    id UUID PRIMARY KEY,
    site_id UUID NOT NULL REFERENCES sites(id),
    name VARCHAR(255),
    registration_token UUID NOT NULL,
    last_ip INET,
    last_seen_at TIMESTAMPTZ,
    client_version VARCHAR(64),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_devices_site_registration_token UNIQUE (site_id, registration_token)
);

CREATE INDEX IF NOT EXISTS ix_devices_site_id ON devices(site_id);
CREATE INDEX IF NOT EXISTS ix_devices_last_seen_at ON devices(last_seen_at);



CREATE TABLE IF NOT EXISTS categories (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(100),
    parent_id UUID REFERENCES categories(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sort_order INTEGER
);

CREATE INDEX IF NOT EXISTS ix_categories_parent_id ON categories(parent_id);
CREATE INDEX IF NOT EXISTS ix_categories_updated_at ON categories(updated_at);



CREATE TABLE IF NOT EXISTS items (
    id UUID PRIMARY KEY,
    sku VARCHAR(100) UNIQUE,
    name VARCHAR(255) NOT NULL,
    category_id UUID REFERENCES categories(id),
    unit VARCHAR(32) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_items_updated_at ON items(updated_at);



CREATE TABLE IF NOT EXISTS events (
    event_uuid UUID PRIMARY KEY,
    site_id UUID NOT NULL REFERENCES sites(id),
    device_id UUID REFERENCES devices(id),
    user_id INTEGER,
    event_type VARCHAR(64) NOT NULL,
    event_datetime TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    schema_version INTEGER NOT NULL DEFAULT 1,
    payload JSONB NOT NULL,
    server_seq BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    payload_hash VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_events_site_id_server_seq ON events(site_id, server_seq);
CREATE INDEX IF NOT EXISTS ix_events_site_id_event_datetime ON events(site_id, event_datetime);
CREATE INDEX IF NOT EXISTS ix_events_event_type ON events(event_type);



CREATE TABLE IF NOT EXISTS balances (
    site_id UUID NOT NULL REFERENCES sites(id),
    item_id UUID NOT NULL REFERENCES items(id),
    qty NUMERIC(18,3) NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (site_id, item_id)
);



CREATE TABLE IF NOT EXISTS user_site_roles (
    user_id INTEGER NOT NULL,
    site_id UUID NOT NULL REFERENCES sites(id),
    role_code VARCHAR(64) NOT NULL,
    PRIMARY KEY (user_id, site_id, role_code)
);