"""operations acceptance and asset registers

Revision ID: 0004_operations_acceptance_asset_registers
Revises: 0003_items_hashtags_reconcile
Create Date: 2026-04-09 18:30:00.000000

"""
from collections.abc import Sequence

from alembic import op


revision: str = "0004_operations_acceptance_asset_registers"
down_revision: str | None = "0003_items_hashtags_reconcile"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


UPGRADE_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS recipients (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        recipient_type VARCHAR(24) NOT NULL DEFAULT 'person',
        display_name VARCHAR(255) NOT NULL,
        normalized_key VARCHAR(255) NOT NULL UNIQUE,
        personnel_no VARCHAR(64),
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        merged_into_id INTEGER REFERENCES recipients (id),
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT ck_recipients_type CHECK (recipient_type IN ('person', 'group', 'department', 'contractor', 'system_repo'))
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_recipients_display_name ON recipients (display_name)",
    "CREATE INDEX IF NOT EXISTS ix_recipients_personnel_no ON recipients (personnel_no)",
    """
    CREATE TABLE IF NOT EXISTS recipient_aliases (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        recipient_id INTEGER NOT NULL REFERENCES recipients (id),
        alias VARCHAR(255) NOT NULL,
        normalized_key VARCHAR(255) NOT NULL UNIQUE,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_recipient_aliases_recipient_id ON recipient_aliases (recipient_id)",
    "ALTER TABLE operations ADD COLUMN IF NOT EXISTS recipient_id INTEGER REFERENCES recipients (id)",
    "ALTER TABLE operations ADD COLUMN IF NOT EXISTS recipient_name_snapshot VARCHAR(255)",
    "ALTER TABLE operations ADD COLUMN IF NOT EXISTS acceptance_required BOOLEAN NOT NULL DEFAULT FALSE",
    "ALTER TABLE operations ADD COLUMN IF NOT EXISTS acceptance_state VARCHAR(16) NOT NULL DEFAULT 'not_required'",
    "ALTER TABLE operations ADD COLUMN IF NOT EXISTS acceptance_resolved_at TIMESTAMP WITH TIME ZONE",
    "ALTER TABLE operations ADD COLUMN IF NOT EXISTS acceptance_resolved_by_user_id UUID REFERENCES users (id)",
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'ck_operations_acceptance_state'
        ) THEN
            ALTER TABLE operations
            ADD CONSTRAINT ck_operations_acceptance_state
            CHECK (acceptance_state IN ('not_required', 'pending', 'in_progress', 'resolved'));
        END IF;
    END
    $$;
    """,
    "ALTER TABLE operation_lines ADD COLUMN IF NOT EXISTS accepted_qty NUMERIC(18, 3) NOT NULL DEFAULT 0",
    "ALTER TABLE operation_lines ADD COLUMN IF NOT EXISTS lost_qty NUMERIC(18, 3) NOT NULL DEFAULT 0",
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'ck_operation_lines_accepted_qty_non_negative'
        ) THEN
            ALTER TABLE operation_lines
            ADD CONSTRAINT ck_operation_lines_accepted_qty_non_negative CHECK (accepted_qty >= 0);
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'ck_operation_lines_lost_qty_non_negative'
        ) THEN
            ALTER TABLE operation_lines
            ADD CONSTRAINT ck_operation_lines_lost_qty_non_negative CHECK (lost_qty >= 0);
        END IF;
    END
    $$;
    """,
    """
    CREATE TABLE IF NOT EXISTS pending_acceptance_balances (
        operation_line_id BIGINT PRIMARY KEY REFERENCES operation_lines (id),
        operation_id UUID NOT NULL REFERENCES operations (id),
        destination_site_id INTEGER NOT NULL REFERENCES sites (id),
        source_site_id INTEGER REFERENCES sites (id),
        item_id INTEGER NOT NULL REFERENCES items (id),
        qty NUMERIC(18, 3) NOT NULL DEFAULT 0,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT ck_pending_acceptance_qty_non_negative CHECK (qty >= 0)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS lost_asset_balances (
        operation_line_id BIGINT PRIMARY KEY REFERENCES operation_lines (id),
        operation_id UUID NOT NULL REFERENCES operations (id),
        site_id INTEGER NOT NULL REFERENCES sites (id),
        source_site_id INTEGER REFERENCES sites (id),
        item_id INTEGER NOT NULL REFERENCES items (id),
        qty NUMERIC(18, 3) NOT NULL DEFAULT 0,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT ck_lost_asset_qty_non_negative CHECK (qty >= 0)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS issued_asset_balances (
        recipient_id INTEGER NOT NULL REFERENCES recipients (id),
        item_id INTEGER NOT NULL REFERENCES items (id),
        qty NUMERIC(18, 3) NOT NULL DEFAULT 0,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT pk_issued_asset_balances PRIMARY KEY (recipient_id, item_id),
        CONSTRAINT ck_issued_asset_qty_non_negative CHECK (qty >= 0)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS operation_acceptance_actions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        operation_id UUID NOT NULL REFERENCES operations (id),
        operation_line_id BIGINT NOT NULL REFERENCES operation_lines (id),
        action_type VARCHAR(64) NOT NULL,
        qty NUMERIC(18, 3) NOT NULL,
        performed_by_user_id UUID NOT NULL REFERENCES users (id),
        recipient_id INTEGER REFERENCES recipients (id),
        notes VARCHAR(500),
        performed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT ck_operation_acceptance_actions_qty_positive CHECK (qty > 0),
        CONSTRAINT ck_operation_acceptance_actions_type CHECK (
            action_type IN ('accept', 'mark_lost', 'found_to_destination', 'return_to_source', 'write_off')
        )
    )
    """,
)


def upgrade() -> None:
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    op.drop_table("operation_acceptance_actions")
    op.drop_table("issued_asset_balances")
    op.drop_table("lost_asset_balances")
    op.drop_table("pending_acceptance_balances")

    op.drop_constraint("ck_operation_lines_lost_qty_non_negative", "operation_lines")
    op.drop_constraint("ck_operation_lines_accepted_qty_non_negative", "operation_lines")
    op.drop_column("operation_lines", "lost_qty")
    op.drop_column("operation_lines", "accepted_qty")

    op.drop_constraint("ck_operations_acceptance_state", "operations")
    op.drop_column("operations", "acceptance_resolved_by_user_id")
    op.drop_column("operations", "acceptance_resolved_at")
    op.drop_column("operations", "acceptance_state")
    op.drop_column("operations", "acceptance_required")
    op.drop_column("operations", "recipient_name_snapshot")
    op.drop_column("operations", "recipient_id")

    op.drop_index("ix_recipient_aliases_recipient_id", table_name="recipient_aliases")
    op.drop_table("recipient_aliases")
    op.drop_index("ix_recipients_personnel_no", table_name="recipients")
    op.drop_index("ix_recipients_display_name", table_name="recipients")
    op.drop_table("recipients")
