"""inventory subjects backfill

Revision ID: 0008_inventory_subjects_backfill
Revises: 0007_temporary_items_phase1
Create Date: 2026-04-22 12:40:00.000000
"""

from collections.abc import Sequence

from alembic import op


revision: str = "0008_inventory_subjects_backfill"
down_revision: str | None = "0007_temporary_items_phase1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


UPGRADE_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS inventory_subjects (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        subject_type VARCHAR(32) NOT NULL,
        item_id INTEGER REFERENCES items (id),
        temporary_item_id INTEGER REFERENCES temporary_items (id),
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        archived_at TIMESTAMP WITH TIME ZONE,
        CONSTRAINT ck_inventory_subjects_subject_type CHECK (subject_type IN ('catalog_item', 'temporary_item'))
    )
    """,
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_inventory_subjects_item_id ON inventory_subjects (item_id) WHERE item_id IS NOT NULL",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_inventory_subjects_temporary_item_id ON inventory_subjects (temporary_item_id) WHERE temporary_item_id IS NOT NULL",
    "CREATE INDEX IF NOT EXISTS ix_inventory_subjects_subject_type ON inventory_subjects (subject_type)",
    "CREATE INDEX IF NOT EXISTS ix_inventory_subjects_item_id ON inventory_subjects (item_id)",
    "CREATE INDEX IF NOT EXISTS ix_inventory_subjects_temporary_item_id ON inventory_subjects (temporary_item_id)",
    """
    INSERT INTO inventory_subjects (subject_type, item_id)
    SELECT 'catalog_item', i.id
    FROM items i
    LEFT JOIN temporary_items ti ON ti.item_id = i.id
    LEFT JOIN inventory_subjects s ON s.item_id = i.id
    WHERE s.id IS NULL
      AND ti.id IS NULL
    """,
    """
    INSERT INTO inventory_subjects (subject_type, temporary_item_id, item_id)
    SELECT 'temporary_item', ti.id, ti.item_id
    FROM temporary_items ti
    LEFT JOIN inventory_subjects s ON s.temporary_item_id = ti.id
    WHERE s.id IS NULL
    """,
    "ALTER TABLE operation_lines ADD COLUMN IF NOT EXISTS inventory_subject_id INTEGER",
    "ALTER TABLE balances ADD COLUMN IF NOT EXISTS inventory_subject_id INTEGER",
    "ALTER TABLE pending_acceptance_balances ADD COLUMN IF NOT EXISTS inventory_subject_id INTEGER",
    "ALTER TABLE lost_asset_balances ADD COLUMN IF NOT EXISTS inventory_subject_id INTEGER",
    "ALTER TABLE issued_asset_balances ADD COLUMN IF NOT EXISTS inventory_subject_id INTEGER",
    """
    UPDATE operation_lines ol
    SET inventory_subject_id = s.id
    FROM inventory_subjects s
    JOIN temporary_items ti ON ti.id = s.temporary_item_id
    WHERE ol.item_id = ti.item_id
      AND ol.inventory_subject_id IS NULL
      AND s.subject_type = 'temporary_item'
    """,
    """
    UPDATE operation_lines ol
    SET inventory_subject_id = s.id
    FROM inventory_subjects s
    WHERE ol.item_id = s.item_id
      AND ol.inventory_subject_id IS NULL
      AND s.subject_type = 'catalog_item'
    """,
    """
    UPDATE balances b
    SET inventory_subject_id = s.id
    FROM inventory_subjects s
    JOIN temporary_items ti ON ti.id = s.temporary_item_id
    WHERE b.item_id = ti.item_id
      AND b.inventory_subject_id IS NULL
      AND s.subject_type = 'temporary_item'
    """,
    """
    UPDATE balances b
    SET inventory_subject_id = s.id
    FROM inventory_subjects s
    WHERE b.item_id = s.item_id
      AND b.inventory_subject_id IS NULL
      AND s.subject_type = 'catalog_item'
    """,
    """
    UPDATE pending_acceptance_balances p
    SET inventory_subject_id = s.id
    FROM inventory_subjects s
    JOIN temporary_items ti ON ti.id = s.temporary_item_id
    WHERE p.item_id = ti.item_id
      AND p.inventory_subject_id IS NULL
      AND s.subject_type = 'temporary_item'
    """,
    """
    UPDATE pending_acceptance_balances p
    SET inventory_subject_id = s.id
    FROM inventory_subjects s
    WHERE p.item_id = s.item_id
      AND p.inventory_subject_id IS NULL
      AND s.subject_type = 'catalog_item'
    """,
    """
    UPDATE lost_asset_balances l
    SET inventory_subject_id = s.id
    FROM inventory_subjects s
    JOIN temporary_items ti ON ti.id = s.temporary_item_id
    WHERE l.item_id = ti.item_id
      AND l.inventory_subject_id IS NULL
      AND s.subject_type = 'temporary_item'
    """,
    """
    UPDATE lost_asset_balances l
    SET inventory_subject_id = s.id
    FROM inventory_subjects s
    WHERE l.item_id = s.item_id
      AND l.inventory_subject_id IS NULL
      AND s.subject_type = 'catalog_item'
    """,
    """
    UPDATE issued_asset_balances iab
    SET inventory_subject_id = s.id
    FROM inventory_subjects s
    JOIN temporary_items ti ON ti.id = s.temporary_item_id
    WHERE iab.item_id = ti.item_id
      AND iab.inventory_subject_id IS NULL
      AND s.subject_type = 'temporary_item'
    """,
    """
    UPDATE issued_asset_balances iab
    SET inventory_subject_id = s.id
    FROM inventory_subjects s
    WHERE iab.item_id = s.item_id
      AND iab.inventory_subject_id IS NULL
      AND s.subject_type = 'catalog_item'
    """,
    """
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'operation_lines' AND column_name = 'item_id'
        ) THEN
            ALTER TABLE operation_lines ALTER COLUMN item_id DROP NOT NULL;
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'balances' AND column_name = 'item_id'
        ) AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
            WHERE c.conrelid = 'balances'::regclass
              AND c.contype = 'p'
              AND a.attname = 'item_id'
        ) THEN
            ALTER TABLE balances ALTER COLUMN item_id DROP NOT NULL;
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'pending_acceptance_balances' AND column_name = 'item_id'
        ) AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
            WHERE c.conrelid = 'pending_acceptance_balances'::regclass
              AND c.contype = 'p'
              AND a.attname = 'item_id'
        ) THEN
            ALTER TABLE pending_acceptance_balances ALTER COLUMN item_id DROP NOT NULL;
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'lost_asset_balances' AND column_name = 'item_id'
        ) AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
            WHERE c.conrelid = 'lost_asset_balances'::regclass
              AND c.contype = 'p'
              AND a.attname = 'item_id'
        ) THEN
            ALTER TABLE lost_asset_balances ALTER COLUMN item_id DROP NOT NULL;
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'issued_asset_balances' AND column_name = 'item_id'
        ) AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
            WHERE c.conrelid = 'issued_asset_balances'::regclass
              AND c.contype = 'p'
              AND a.attname = 'item_id'
        ) THEN
            ALTER TABLE issued_asset_balances ALTER COLUMN item_id DROP NOT NULL;
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'fk_operation_lines_inventory_subject_id'
        ) THEN
            ALTER TABLE operation_lines
            ADD CONSTRAINT fk_operation_lines_inventory_subject_id
            FOREIGN KEY (inventory_subject_id) REFERENCES inventory_subjects (id);
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'fk_balances_inventory_subject_id'
        ) THEN
            ALTER TABLE balances
            ADD CONSTRAINT fk_balances_inventory_subject_id
            FOREIGN KEY (inventory_subject_id) REFERENCES inventory_subjects (id);
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'fk_pending_acceptance_balances_inventory_subject_id'
        ) THEN
            ALTER TABLE pending_acceptance_balances
            ADD CONSTRAINT fk_pending_acceptance_balances_inventory_subject_id
            FOREIGN KEY (inventory_subject_id) REFERENCES inventory_subjects (id);
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'fk_lost_asset_balances_inventory_subject_id'
        ) THEN
            ALTER TABLE lost_asset_balances
            ADD CONSTRAINT fk_lost_asset_balances_inventory_subject_id
            FOREIGN KEY (inventory_subject_id) REFERENCES inventory_subjects (id);
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'fk_issued_asset_balances_inventory_subject_id'
        ) THEN
            ALTER TABLE issued_asset_balances
            ADD CONSTRAINT fk_issued_asset_balances_inventory_subject_id
            FOREIGN KEY (inventory_subject_id) REFERENCES inventory_subjects (id);
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'balances' AND column_name = 'inventory_subject_id'
        ) THEN
            ALTER TABLE balances ALTER COLUMN inventory_subject_id SET NOT NULL;
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'pending_acceptance_balances' AND column_name = 'inventory_subject_id'
        ) THEN
            ALTER TABLE pending_acceptance_balances ALTER COLUMN inventory_subject_id SET NOT NULL;
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'lost_asset_balances' AND column_name = 'inventory_subject_id'
        ) THEN
            ALTER TABLE lost_asset_balances ALTER COLUMN inventory_subject_id SET NOT NULL;
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'issued_asset_balances' AND column_name = 'inventory_subject_id'
        ) THEN
            ALTER TABLE issued_asset_balances ALTER COLUMN inventory_subject_id SET NOT NULL;
        END IF;
    END
    $$;
    """,
    "CREATE INDEX IF NOT EXISTS ix_operation_lines_inventory_subject_id ON operation_lines (inventory_subject_id)",
    "CREATE INDEX IF NOT EXISTS ix_balances_inventory_subject_id ON balances (inventory_subject_id)",
    "CREATE INDEX IF NOT EXISTS ix_pending_acceptance_balances_inventory_subject_id ON pending_acceptance_balances (inventory_subject_id)",
    "CREATE INDEX IF NOT EXISTS ix_lost_asset_balances_inventory_subject_id ON lost_asset_balances (inventory_subject_id)",
    "CREATE INDEX IF NOT EXISTS ix_issued_asset_balances_inventory_subject_id ON issued_asset_balances (inventory_subject_id)",
    """
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'balances_pkey'
              AND conrelid = 'balances'::regclass
        ) THEN
            ALTER TABLE balances DROP CONSTRAINT balances_pkey;
        END IF;

        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'balances_pkey'
              AND conrelid = 'balances'::regclass
        ) THEN
            ALTER TABLE balances ADD CONSTRAINT balances_pkey PRIMARY KEY (site_id, inventory_subject_id);
        END IF;
    END
    $$;
    """,
    """
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'pk_issued_asset_balances'
              AND conrelid = 'issued_asset_balances'::regclass
        ) THEN
            ALTER TABLE issued_asset_balances DROP CONSTRAINT pk_issued_asset_balances;
        END IF;

        IF EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'issued_asset_balances_pkey'
              AND conrelid = 'issued_asset_balances'::regclass
        ) THEN
            ALTER TABLE issued_asset_balances DROP CONSTRAINT issued_asset_balances_pkey;
        END IF;

        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'issued_asset_balances_pkey'
              AND conrelid = 'issued_asset_balances'::regclass
        ) THEN
            ALTER TABLE issued_asset_balances
            ADD CONSTRAINT issued_asset_balances_pkey PRIMARY KEY (recipient_id, inventory_subject_id);
        END IF;
    END
    $$;
    """,
)


def upgrade() -> None:
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_issued_asset_balances_inventory_subject_id")
    op.execute("DROP INDEX IF EXISTS ix_lost_asset_balances_inventory_subject_id")
    op.execute("DROP INDEX IF EXISTS ix_pending_acceptance_balances_inventory_subject_id")
    op.execute("DROP INDEX IF EXISTS ix_balances_inventory_subject_id")
    op.execute("DROP INDEX IF EXISTS ix_operation_lines_inventory_subject_id")

    op.execute("ALTER TABLE issued_asset_balances DROP CONSTRAINT IF EXISTS issued_asset_balances_pkey")
    op.execute(
        "ALTER TABLE issued_asset_balances ADD CONSTRAINT issued_asset_balances_pkey PRIMARY KEY (recipient_id, item_id)"
    )
    op.execute("ALTER TABLE balances DROP CONSTRAINT IF EXISTS balances_pkey")
    op.execute("ALTER TABLE balances ADD CONSTRAINT balances_pkey PRIMARY KEY (site_id, item_id)")

    op.execute("ALTER TABLE issued_asset_balances DROP CONSTRAINT IF EXISTS fk_issued_asset_balances_inventory_subject_id")
    op.execute("ALTER TABLE lost_asset_balances DROP CONSTRAINT IF EXISTS fk_lost_asset_balances_inventory_subject_id")
    op.execute(
        "ALTER TABLE pending_acceptance_balances DROP CONSTRAINT IF EXISTS fk_pending_acceptance_balances_inventory_subject_id"
    )
    op.execute("ALTER TABLE balances DROP CONSTRAINT IF EXISTS fk_balances_inventory_subject_id")
    op.execute("ALTER TABLE operation_lines DROP CONSTRAINT IF EXISTS fk_operation_lines_inventory_subject_id")

    op.execute("ALTER TABLE issued_asset_balances DROP COLUMN IF EXISTS inventory_subject_id")
    op.execute("ALTER TABLE lost_asset_balances DROP COLUMN IF EXISTS inventory_subject_id")
    op.execute("ALTER TABLE pending_acceptance_balances DROP COLUMN IF EXISTS inventory_subject_id")
    op.execute("ALTER TABLE balances DROP COLUMN IF EXISTS inventory_subject_id")
    op.execute("ALTER TABLE operation_lines DROP COLUMN IF EXISTS inventory_subject_id")

    op.execute("DROP INDEX IF EXISTS ix_inventory_subjects_temporary_item_id")
    op.execute("DROP INDEX IF EXISTS ix_inventory_subjects_item_id")
    op.execute("DROP INDEX IF EXISTS ix_inventory_subjects_subject_type")
    op.execute("DROP INDEX IF EXISTS uq_inventory_subjects_temporary_item_id")
    op.execute("DROP INDEX IF EXISTS uq_inventory_subjects_item_id")
    op.execute("DROP TABLE IF EXISTS inventory_subjects")

