"""add_snapshots_and_deleted_fields

Revision ID: 1d1801ed5535
Revises: 0004_operations_acceptance_asset_registers
Create Date: 2026-04-10 14:19:16.848080

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1d1801ed5535'
down_revision: Union[str, Sequence[str], None] = '0004_operations_acceptance_asset_registers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('categories', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.create_index('ix_categories_deleted_at', 'categories', ['deleted_at'], unique=False)
    op.add_column('items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('items', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.create_index('ix_items_deleted_at', 'items', ['deleted_at'], unique=False)
    op.add_column('operation_lines', sa.Column('item_name_snapshot', sa.String(length=255), nullable=True))
    op.add_column('operation_lines', sa.Column('item_sku_snapshot', sa.String(length=100), nullable=True))
    op.add_column('operation_lines', sa.Column('unit_name_snapshot', sa.String(length=100), nullable=True))
    op.add_column('operation_lines', sa.Column('unit_symbol_snapshot', sa.String(length=20), nullable=True))
    op.add_column('operation_lines', sa.Column('category_name_snapshot', sa.String(length=255), nullable=True))
    op.add_column('recipients', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recipients', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.create_index('ix_recipients_deleted_at', 'recipients', ['deleted_at'], unique=False)
    op.add_column('units', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('units', sa.Column('deleted_by_user_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('uq_units_code'), table_name='units')
    op.create_index('ix_units_deleted_at', 'units', ['deleted_at'], unique=False)
    op.create_unique_constraint(None, 'units', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_units_code', 'units', type_='unique')
    op.drop_index('ix_units_deleted_at', table_name='units')
    op.create_index(op.f('uq_units_code'), 'units', ['code'], unique=True)
    op.drop_column('units', 'deleted_by_user_id')
    op.drop_column('units', 'deleted_at')
    op.drop_index('ix_recipients_deleted_at', table_name='recipients')
    op.drop_column('recipients', 'deleted_by_user_id')
    op.drop_column('recipients', 'deleted_at')
    op.drop_column('operation_lines', 'category_name_snapshot')
    op.drop_column('operation_lines', 'unit_symbol_snapshot')
    op.drop_column('operation_lines', 'unit_name_snapshot')
    op.drop_column('operation_lines', 'item_sku_snapshot')
    op.drop_column('operation_lines', 'item_name_snapshot')
    op.drop_index('ix_items_deleted_at', table_name='items')
    op.drop_column('items', 'deleted_by_user_id')
    op.drop_column('items', 'deleted_at')
    op.drop_index('ix_categories_deleted_at', table_name='categories')
    op.drop_column('categories', 'deleted_by_user_id')
    op.drop_column('categories', 'deleted_at')
    # ### end Alembic commands ###
